### ISSUE TITLE
Hardcoded API version

### ISSUE THREAD

**Issue by niclasohrlund** [tombosmansibm/pleasant_lookup#1]
Hi! 

Seems Pleasant Server API version is hard coded to v5, is there a plan to release for v6?
Im trying this in AWX and have not been able to make this plugin work. Simple lookup returns "ok" but msg is empty and no login to Pleasant logs.

Running manual tasks like this works and i get a login in Pleasant logs:

# tasks file
- name: set user (use -e pleasant_user=your_user to set the user beforehand)
  set_fact:
    pleasant_user: ""

- name: Set pleasant password
  tags: [always]
  set_fact:
    pleasant_password: ""
    pleasant_host: ""
    pleasant_search_term: ""
    pleasant_filter_username: ""

- name: Get access token from pleasant
  uri:
    url: "{{ pleasant_host }}/oauth2/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: password
      username: "{{ pleasant_user }}"
      password: "{{ pleasant_password }}"
  register: _pleasant_at

- name: "Search for item {{ pleasant_search_term }}"
  uri:
    url: "{{ pleasant_host }}/api/v6/rest/search"
    method: POST
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ _pleasant_at.json.access_token }}"
    body_format: json
    body:
      Search: "{{ pleasant_search_term }}"
  register: _pleasant_searchresult
- debug:
    var: _pleasant_searchresult

**Comment by niclasohrlund** [comment]
I can tell you we found the issue. The lookup should not specify pleasant_host='https://pleasant.com:10001' but rather the url only.

Documentation says this:
debug: msg="{{ lookup('tombosmansibm.pleasant_lookup.password', pleasant_host='https://pleasant.com:10001', username='bob', password='hunter2', pleasant_search='itemname') }}"

Correct way is this:
debug: msg="{{ lookup('tombosmansibm.pleasant_lookup.password', 'https://pleasant.com:10001', username='bob', password='hunter2', pleasant_search='itemname') }}"

My playbook look like this and it works:

---
- name: blablabla
  hosts: localhost
  tasks:
  - name: Set variables
    set_fact:
      pleasant_user: ws_ansible
      pleasant_password: ""
      pleasant_host: ""
      pleasant_search_entry: 'server01'
  - name: password


    debug: msg="{{ lookup('tombosmansibm.pleasant_lookup.password', pleasant_host, username=pleasant_user, password=pleasant_password, pleasant_search=pleasant_search_entry) }}"

**Comment by tombosmansibm** [comment]
Thanks for your remarks, I've updated the code accordingly.
Sorry about the delay !

I was not able to test if using "v6" actually works (no Pleasant server available to me with that version), but at least it's possible now.
