### ISSUE TITLE
Could you please release the current (main) verison ?

### ISSUE THREAD

**Issue by marcosdiez** [tombosmansibm/pleasant_lookup#4]
I sent you a PR last Friday which you already merged ( https://github.com/tombosmansibm/pleasant_lookup/pull/3 ). Thank you for that.

I wish, though, my whole team could use it. So could you please create a new release with the latest code in `main` ?

Thank you in advance!

**Comment by tombosmansibm** [comment]
Hi Marcos, I've updated this collection to v1.2.0 on galaxy .
